# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
# mode: light, dark, or system.
# color: include blue, cyan, green, indigo, purple, red, rose, sky, teal, and zinc.
# appearance:
#   mode: system
#   color: sky
appearance:
  theme_day: jmb
  theme_night: minimal
  font: minimal
  font_size: L

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: 'jmbruel'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    show_translations: true
    hide_language_name: true
    logo:
      text: "Jean-Michel Bruel"

# Site footer
footer:
  copyright:
    notice: '© {year} ACDC. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/jmbruel/netlify'
    content_dir: content
    branch: main

# Personalization
editable: true
